color: null
fieldLayouts:
  e342e3fe-03f0-44f8-91f9-d145718e074c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 00d91f6e-cd53-42b6-a558-a836dd259532
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8cc584a8-5b3f-4841-b7fa-6363cf607b99
        userCondition: null
handle: productsPage
hasTitleField: true
icon: ''
name: 'products page'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
