altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  72c1da8a-e03e-4100-8012-f1004f2fc5d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d667abc2-bee1-48d3-8a67-f7ec5cf2d386
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0a507a6d-bf4e-42d7-bcb4-101469145bce
        userCondition: null
fs: assets
handle: assets
name: Assets
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
