fieldLayouts:
  869c121b-a411-4f88-99e1-070db95b4fcc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f4d28f5-9922-44b0-9c5d-9682a7078519 # Cart Icon
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7106d1d2-f9b9-4513-bf21-5f07c1fe5f51
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 72911f3b-e1ce-4c97-81c3-b6be6ce417c8 # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46c2f8a1-d1d5-44fc-8156-2ed2d6da7d21
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: c5b4e88f-e1b4-45a8-950d-6b4e83dcf0fd
        userCondition: null
handle: headerImages
name: 'Header images'
sortOrder: 2
